name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r releases/plugin-release.zip . -x ".git/*" ".github/*" "releases/*" "README.md"
    - name: Release to Github
      run: echo "Release"